namespace CapyEngine.UtilsNode
{
    public enum ObjectID
    {
        VOID, STONE, DIRT, DIRT_GRASS, PLAYER_IDLE, PLAYER_RUN, PLAYER_JUMP,
        VINE, MINERAL_BLACK, MINERAL_PINK, MINERAL_PURPLE, MINERAL_WHITE,
        STONE_DIRT, STONE_GRASS, GRASS, FIRE, TNT, TNT_ONFIRE, FLOWER_BLUE,
        FLOWER_RED, FLOWER_WHITE, FLOWER_PURPLE, FLOWER_PINK
    }
}
